import { UserRole } from '../types';
import { PermissionKey } from './auth.types';

export const ROLE_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  STAFF_COORDINATOR: [
    'dashboard:view-staff',
    'team:create',
    'team:view-assigned',
    'team:edit',
    'team:delete',
    'team:export',
    'member:add',
    'member:remove',
    'member:assign-role',
    'member:view-roster',
    'task:create',
    'task:edit-any',
    'task:delete',
    'task:assign',
    'task:change-status',
    'document:upload',
    'document:view-team',
    'document:view-coordinator-only',
    'document:delete',
    'document:analyze-consistency',
    'discussion:create',
    'discussion:view',
    'discussion:reply',
    'chat:access-own-team',
    'contribution:view-own',
    'contribution:view-team',
    'contribution:view-staff-analytics',
    'ai:run-team-analysis',
    'ai:view-staff-insights',
    'ai:view-student-insights',
    'gap:view',
    'gap:resolve',
    'profile:edit-own',
    'profile:view-public',
    'profile:view-private-staff',
    'teammate:search',
    'collaboration:request',
    'collaboration:respond',
    'settings:manage',
    'audit:view'
  ],

  TEAM_LEADER: [
    'dashboard:view-leader',
    'team:view-own',
    'member:view-roster',
    'task:create',
    'task:edit-own',
    'task:assign',
    'task:change-status',
    'document:upload',
    'document:view-team',
    'discussion:create',
    'discussion:view',
    'discussion:reply',
    'chat:access-own-team',
    'contribution:view-own',
    'contribution:view-team',
    'ai:view-student-insights',
    'gap:view',
    'profile:edit-own',
    'profile:view-public',
    'teammate:search',
    'collaboration:request',
    'collaboration:respond',
    'settings:manage'
  ],

  TEAM_MEMBER: [
    'dashboard:view-member',
    'team:view-own',
    'member:view-roster',
    'task:edit-own',
    'task:change-status',
    'document:upload',
    'document:view-team',
    'discussion:create',
    'discussion:view',
    'discussion:reply',
    'chat:access-own-team',
    'contribution:view-own',
    'ai:view-student-insights',
    'profile:edit-own',
    'profile:view-public',
    'teammate:search',
    'collaboration:request',
    'collaboration:respond',
    'settings:manage'
  ],

  DEPARTMENT_HEAD: [
    'dashboard:view-department',
    'team:view-department',
    'contribution:view-staff-analytics',
    'ai:view-staff-insights',
    'profile:view-public',
    'settings:manage',
    'audit:view'
  ]
};
